package np.com.nepalikeyboard.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp
import np.com.nepalikeyboard.data.PaletteId

/**
 * Palette definitions.
 *
 * Material 3 "Expressive" treats containers as tonal steps of a single seed.
 * Rather than shipping hundreds of hard-coded hex values, every palette below
 * declares a small, curated set of *anchors* (primary / secondary / tertiary /
 * accent and the surface pair) and [schemeFrom] derives the remaining ~20 M3
 * roles from them with deterministic tonal interpolation. That keeps the eight
 * generated schemes internally consistent and makes adding a palette a
 * five-line change.
 */
@Immutable
internal data class PaletteAnchors(
    val primary: Color,
    val primaryContainer: Color,
    val secondary: Color,
    val secondaryContainer: Color,
    val tertiary: Color,
    val tertiaryContainer: Color,
    val accent: Color,
    val surfaceLight: Color,
    val surfaceDark: Color,
    val onPrimaryLight: Color = Color.White,
    val onPrimaryDark: Color = Color(0xFF161022),
    val onContainerLight: Color = Color(0xFF1B1030),
    val onContainerDark: Color = Color(0xFFEDE3FF),
)

// ---------------------------------------------------------------------------
// Fallback palettes (used when Material You dynamic color is off/unavailable)
// ---------------------------------------------------------------------------

/** Himalaya: the default. Himalayan twilight indigo with snow-lit containers. */
internal val HimalayaPalette = PaletteAnchors(
    primary = Color(0xFF5B3FD1),
    primaryContainer = Color(0xFFE7DEFF),
    secondary = Color(0xFF5D5A73),
    secondaryContainer = Color(0xFFE3DFF6),
    tertiary = Color(0xFF8A4A6B),
    tertiaryContainer = Color(0xFFFFD8E9),
    accent = Color(0xFF7F5AF0),
    surfaceLight = Color(0xFFFBF8FF),
    surfaceDark = Color(0xFF131018),
)

/** Rhododendron: the national flower. Warm crimson on rose-tinted paper. */
internal val RhododendronPalette = PaletteAnchors(
    primary = Color(0xFFB3244A),
    primaryContainer = Color(0xFFFFD9DF),
    secondary = Color(0xFF76565B),
    secondaryContainer = Color(0xFFFFD9DE),
    tertiary = Color(0xFF7C5733),
    tertiaryContainer = Color(0xFFFFDCBF),
    accent = Color(0xFFE0245E),
    surfaceLight = Color(0xFFFFF8F8),
    surfaceDark = Color(0xFF191113),
)

/** Mustard field: Terai mustard bloom. Golden primary on warm neutrals. */
internal val MustardPalette = PaletteAnchors(
    primary = Color(0xFF8A6100),
    primaryContainer = Color(0xFFFFDF9B),
    secondary = Color(0xFF6E5C3E),
    secondaryContainer = Color(0xFFF9DFBB),
    tertiary = Color(0xFF4C6543),
    tertiaryContainer = Color(0xFFCEEBC2),
    accent = Color(0xFFD99E00),
    surfaceLight = Color(0xFFFFF8F1),
    surfaceDark = Color(0xFF17120A),
)

/** Kathmandu Indigo: brick-and-indigo Kathmandu valley dusk. */
internal val IndigoPalette = PaletteAnchors(
    primary = Color(0xFF2F4C9C),
    primaryContainer = Color(0xFFDBE1FF),
    secondary = Color(0xFF575E71),
    secondaryContainer = Color(0xFFDBE2F9),
    tertiary = Color(0xFFB3261E),
    tertiaryContainer = Color(0xFFFFDAD6),
    accent = Color(0xFF3B62C9),
    surfaceLight = Color(0xFFFAF9FF),
    surfaceDark = Color(0xFF10121A),
)

internal fun paletteAnchors(id: PaletteId): PaletteAnchors = when (id) {
    PaletteId.HIMALAYA -> HimalayaPalette
    PaletteId.RHODODENDRON -> RhododendronPalette
    PaletteId.MUSTARD -> MustardPalette
    PaletteId.INDIGO -> IndigoPalette
}

// ---------------------------------------------------------------------------
// Derivation
// ---------------------------------------------------------------------------

private const val BLACK_TONE = 0f
private const val WHITE_TONE = 1f

/**
 * Builds a complete [ColorScheme] from [PaletteAnchors].
 *
 * The surface-container ladder is generated by interpolating the palette
 * surface towards its primary/secondary containers, which is what makes the
 * keyboard's tonal elevation read as one family in both light and dark mode.
 */
internal fun schemeFrom(anchors: PaletteAnchors, dark: Boolean): ColorScheme {
    val surface = if (dark) anchors.surfaceDark else anchors.surfaceLight
    val onSurface = if (dark) Color(0xFFE7E1EA) else Color(0xFF1B1B1F)
    val onSurfaceVariant = if (dark) Color(0xFFC9C4D0) else Color(0xFF48454E)
    val blendTint = if (dark) anchors.primary else anchors.secondary

    // The tonal ladder: lowest = furthest from the wallpaper tone.
    val lowest = lerp(surface, if (dark) Color.Black else Color.White, if (dark) 0.35f else 0.55f)
    val low = lerp(surface, blendTint, if (dark) 0.04f else 0.03f)
    val container = lerp(surface, blendTint, if (dark) 0.09f else 0.06f)
    val containerHigh = lerp(surface, blendTint, if (dark) 0.14f else 0.10f)
    val containerHighest = lerp(surface, blendTint, if (dark) 0.19f else 0.14f)
    val bright = lerp(surface, if (dark) Color.White else Color.White, if (dark) 0.06f else 0f)

    val primary = if (dark) lighten(anchors.primary, 0.22f) else anchors.primary
    val primaryContainer = if (dark) darken(anchors.primary, 0.42f) else anchors.primaryContainer
    val secondary = if (dark) lighten(anchors.secondary, 0.24f) else anchors.secondary
    val secondaryContainer = if (dark) darken(anchors.secondary, 0.40f) else anchors.secondaryContainer
    val tertiary = if (dark) lighten(anchors.tertiary, 0.24f) else anchors.tertiary
    val tertiaryContainer = if (dark) darken(anchors.tertiary, 0.40f) else anchors.tertiaryContainer

    val onPrimary = if (dark) anchors.onPrimaryDark else anchors.onPrimaryLight
    val onPrimaryContainer = if (dark) anchors.onContainerDark else anchors.onContainerLight
    val error = if (dark) Color(0xFFFFB4AB) else Color(0xFFBA1A1A)
    val errorContainer = if (dark) Color(0xFF93000A) else Color(0xFFFFDAD6)

    val base = if (dark) {
        darkColorScheme(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            inversePrimary = darken(primary, 0.25f),
            secondary = secondary,
            onSecondary = onPrimary,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onPrimaryContainer,
            tertiary = tertiary,
            onTertiary = onPrimary,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onPrimaryContainer,
            error = error,
            onError = Color(0xFF690005),
            errorContainer = errorContainer,
            onErrorContainer = Color(0xFFFFDAD6),
            background = surface,
            onBackground = onSurface,
            surface = surface,
            onSurface = onSurface,
            surfaceVariant = containerHighest,
            onSurfaceVariant = onSurfaceVariant,
            surfaceTint = primary,
            inverseSurface = onSurface,
            inverseOnSurface = surface,
            outline = lerp(onSurfaceVariant, surface, 0.35f),
            outlineVariant = lerp(onSurfaceVariant, surface, 0.72f),
            scrim = Color.Black,
            surfaceBright = bright,
            surfaceDim = lowest,
            surfaceContainerLowest = lowest,
            surfaceContainerLow = low,
            surfaceContainer = container,
            surfaceContainerHigh = containerHigh,
            surfaceContainerHighest = containerHighest,
        )
    } else {
        lightColorScheme(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            inversePrimary = lighten(primary, 0.35f),
            secondary = secondary,
            onSecondary = onPrimary,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onPrimaryContainer,
            tertiary = tertiary,
            onTertiary = onPrimary,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onPrimaryContainer,
            error = error,
            onError = Color.White,
            errorContainer = errorContainer,
            onErrorContainer = Color(0xFF410E0B),
            background = surface,
            onBackground = onSurface,
            surface = surface,
            onSurface = onSurface,
            surfaceVariant = containerHigh,
            onSurfaceVariant = onSurfaceVariant,
            surfaceTint = primary,
            inverseSurface = Color(0xFF313033),
            inverseOnSurface = Color(0xFFF4EFF4),
            outline = lerp(onSurfaceVariant, surface, 0.35f),
            outlineVariant = lerp(onSurfaceVariant, surface, 0.68f),
            scrim = Color.Black,
            surfaceBright = bright,
            surfaceDim = lerp(surface, Color.Black, 0.08f),
            surfaceContainerLowest = Color.White,
            surfaceContainerLow = low,
            surfaceContainer = container,
            surfaceContainerHigh = containerHigh,
            surfaceContainerHighest = containerHighest,
        )
    }
    return base
}

/**
 * AMOLED mode: true-black surfaces with the accent hue preserved. Used by the
 * keyboard so that OLED panels draw pure black between key caps.
 */
internal fun amoledify(scheme: ColorScheme): ColorScheme = scheme.copy(
    background = Color.Black,
    surface = Color.Black,
    surfaceDim = Color.Black,
    surfaceBright = Color(0xFF131313),
    surfaceContainerLowest = Color(0xFF000000),
    surfaceContainerLow = Color(0xFF0A0A0C),
    surfaceContainer = Color(0xFF101014),
    surfaceContainerHigh = Color(0xFF16161B),
    surfaceContainerHighest = Color(0xFF1D1D23),
    surfaceVariant = Color(0xFF1D1D23),
)

// ---------------------------------------------------------------------------
// Tonal maths (no HCT dependency, deterministic and allocation free)
// ---------------------------------------------------------------------------

private fun lighten(color: Color, by: Float): Color =
    lerp(color, Color.White, by.coerceIn(BLACK_TONE, WHITE_TONE))

private fun darken(color: Color, by: Float): Color =
    lerp(color, Color.Black, by.coerceIn(BLACK_TONE, WHITE_TONE))
