package np.com.nepalikeyboard.util

import androidx.compose.runtime.Immutable

/** Emoji panel categories, in tab order. */
enum class EmojiCategory(val labelResHint: String) {
    RECENT("Recent"),
    SMILEYS("Smileys"),
    PEOPLE("People"),
    ANIMALS("Animals"),
    FOOD("Food"),
    TRAVEL("Travel"),
    ACTIVITIES("Activities"),
    OBJECTS("Objects"),
    SYMBOLS("Symbols"),
    FLAGS("Flags"),
}

/**
 * One emoji with its search keywords.
 *
 * Keywords intentionally contain both English and Nepali terms so that search
 * works whichever language the user thinks in ("माया" and "love" both find ❤️).
 * The catalog is compiled into the APK, parses nothing at startup and needs no
 * assets: the whole table is ~400 entries and about 20 KB of DEX.
 */
@Immutable
class EmojiEntry(
    val emoji: String,
    val keywords: String,
)

/**
 * Bundled emoji catalog.
 *
 * Deliberately a curated subset (the Unicode set that actually gets used in
 * Nepali chat) rather than all 3,600 codepoints, which keeps the panel fast and
 * the search meaningful.
 */
object EmojiCatalog {

    private fun entry(emoji: String, keywords: String) = EmojiEntry(emoji, keywords)

    val SMILEYS: List<EmojiEntry> = listOf(
        entry("\uD83D\uDE00", "grinning smile खुसी हाँसो face happy"),
        entry("\uD83D\uDE03", "smile खुसी happy face"),
        entry("\uD83D\uDE04", "smile eyes खुसी हाँसो happy"),
        entry("\uD83D\uDE01", "grin beaming हाँसो grin"),
        entry("\uD83D\uDE06", "laugh squint हाँसो laughing"),
        entry("\uD83D\uDE05", "sweat smile relief"),
        entry("\uD83E\uDD23", "joy tears हाँसो laughing"),
        entry("\uD83D\uDE02", "joy laugh crying happy"),
        entry("\uD83D\uDE42", "slight smile fine ठिक"),
        entry("\uD83D\uDE43", "upside down silly"),
        entry("\uD83D\uDE09", "wink आँखा wink"),
        entry("\uD83D\uDE0A", "blush smile माया love face"),
        entry("\uD83D\uDE07", "halo angel"),
        entry("\uD83E\uDD70", "smiling hearts love माया adoration"),
        entry("\uD83D\uDE0D", "heart eyes love माया crush"),
        entry("\uD83E\uDD73", "star struck wow"),
        entry("\uD83D\uDE0B", "yum tasty मिठो delicious"),
        entry("\uD83D\uDE1C", "zany tongue silly"),
        entry("\uD83D\uDE1D", "tongue squint playful"),
        entry("\uD83E\uDD2A", "squint tongue silly"),
        entry("\uD83D\uDCB0", "money bag पैसा rich"),
        entry("\uD83E\uDD11", "money mouth"),
        entry("\uD83E\uDD2D", "hand over mouth surprise"),
        entry("\uD83E\uDD2B", "hugging hug माया warm"),
        entry("\uD83E\uDD17", "thinking soch विचार hmm"),
        entry("\uD83E\uDD14", "thinking hmm soch"),
        entry("\uD83D\uDE10", "neutral meh"),
        entry("\uD83D\uDE11", "expressionless flat"),
        entry("\uD83D\uDE36", "no mouth silent"),
        entry("\uD83D\uDE44", "smirk"),
        entry("\uD83D\uDE0F", "unamused meh"),
        entry("\uD83D\uDE12", "rolling eyes"),
        entry("\uD83D\uDE13", "grimace awkward"),
        entry("\uD83E\uDD25", "lying pinocchio"),
        entry("\uD83E\uDD24", "relieved peaceful"),
        entry("\uD83D\uDE05", "sweat smile"),
        entry("\uD83D\uDE2C", "sleeping suttे sleep"),
        entry("\uD83D\uDE34", "sleeping zzz suttे"),
        entry("\uD83D\uDE37", "mask sick"),
        entry("\uD83E\uDD12", "thermometer sick jworo"),
        entry("\uD83E\uDD15", "head bandage hurt"),
        entry("\uD83E\uDD22", "nauseated sick"),
        entry("\uD83E\uDD27", "sneezing"),
        entry("\uD83D\uDE35", "dizzy tired"),
        entry("\uD83E\uDD74", "woozy drunk"),
        entry("\uD83D\uDE30", "worried चिन्ता"),
        entry("\uD83D\uDE25", "sad relieved"),
        entry("\uD83D\uDE22", "cry रुवाइ sad आँसु"),
        entry("\uD83D\uDE2D", "loudly crying sad रुवाइ"),
        entry("\uD83D\uDE31", "screaming fear डर"),
        entry("\uD83D\uDE28", "fearful डर"),
        entry("\uD83D\uDE26", "frowning sad"),
        entry("\uD83D\uDE27", "anguished"),
        entry("\uD83D\uDE29", "open mouth wow"),
        entry("\uD83D\uDE2E", "hushed surprise"),
        entry("\uD83D\uDE24", "angry रिस anger"),
        entry("\uD83D\uDE20", "angry रिस rage"),
        entry("\uD83D\uDE21", "pouting mad रिस"),
        entry("\uD83E\uDD2C", "cursing swearing"),
        entry("\uD83D\uDE08", "devil शैतान"),
        entry("\uD83D\uDC7F", "imp goblin"),
        entry("\uD83D\uDC7B", "ghost bhut"),
        entry("\uD83D\uDC7D", "alien"),
        entry("\uD83E\uDD16", "robot"),
        entry("\uD83D\uDCA9", "poop"),
        entry("\uD83D\uDE3A", "cat smile"),
        entry("\uD83D\uDE38", "cat grin"),
        entry("\uD83D\uDE39", "cat joy"),
        entry("\uD83D\uDE3B", "heart cat love"),
        entry("\uD83D\uDE3C", "cat smirk"),
        entry("\uD83D\uDE40", "cat wow"),
        entry("\uD83D\uDE3F", "cat cry"),
        entry("\uD83D\uDE3E", "cat scream"),
        entry("\uD83D\uDE33", "flushed shy लाज"),
        entry("\uD83D\uDE32", "dizzy star"),
        entry("\uD83D\uDE0C", "relaxed relief"),
        entry("\uD83D\uDE0E", "cool sunglasses राम्रो"),
        entry("\uD83E\uDD13", "nerd"),
        entry("\uD83E\uDD78", "monocle"),
        entry("\uD83E\uDD79", "exploding head mind blown"),
        entry("\uD83E\uDD2F", "cowboy"),
        entry("\uD83E\uDD75", "partying party"),
        entry("\uD83E\uDD76", "hot melting"),
        entry("\uD83D\uDE15", "confused"),
        entry("\uD83D\uDE16", "worried sad"),
        entry("\uD83D\uDE1F", "worried sad"),
        entry("\uD83D\uDE23", "persevere tired"),
        entry("\uD83D\uDE17", "kissing"),
        entry("\uD83D\uDE19", "kissing smiling"),
        entry("\uD83D\uDE1A", "kiss"),
        entry("\uD83D\uDE18", "kissing closed eyes"),
        entry("\uD83E\uDD72", "star eyes"),
        entry("\uD83D\uDE1E", "disappointed sad"),
        entry("\uD83D\uDE41", "upset sad दुखी"),
        entry("\uD83D\uDE2B", "tired exhausted"),
        entry("\uD83E\uDD71", "yawn sleepy"),
        entry("\uD83D\uDE14", "pensive soch"),
        entry("\uD83D\uDE1B", "tongue out"),
    )

    val PEOPLE: List<EmojiEntry> = listOf(
        entry("\uD83D\uDC4B", "wave नमस्ते hello hi"),
        entry("\uD83E\uDD1A", "raised back hand"),
        entry("\uD83D\uDD90\uFE0F", "raised hand palm"),
        entry("\u270B", "raised hand high five"),
        entry("\uD83D\uDC4C", "ok ठिक perfect"),
        entry("\uD83E\uDD0C", "pinched fingers"),
        entry("\u270C\uFE0F", "victory जित"),
        entry("\uD83E\uDD1E", "crossed fingers luck"),
        entry("\uD83E\uDD1F", "love you sign"),
        entry("\uD83E\uDD18", "metal rock"),
        entry("\uD83D\uDC4D", "thumbs up राम्रो like"),
        entry("\uD83D\uDC4E", "thumbs down नराम्रो dislike"),
        entry("\u270A", "fist"),
        entry("\uD83D\uDC4A", "fist bump punch"),
        entry("\uD83E\uDD1B", "left fist"),
        entry("\uD83D\uDC4F", "clap ताली applause"),
        entry("\uD83D\uDE4C", "raised hands hooray"),
        entry("\uD83D\uDC50", "open hands"),
        entry("\uD83E\uDD32", "palms up"),
        entry("\uD83E\uDD1D", "handshake भेट meet"),
        entry("\uD83D\uDE4F", "folded hands नमस्ते pranam please"),
        entry("\uD83D\uDC85", "nail polish"),
        entry("\uD83E\uDD33", "flex muscle strong"),
        entry("\uD83D\uDC46", "point up"),
        entry("\uD83D\uDC47", "point down"),
        entry("\uD83D\uDC48", "point left"),
        entry("\uD83D\uDC49", "point right"),
        entry("\uD83D\uDC4B", "wave bye"),
        entry("\uD83E\uDD1C", "rock paper scissors"),
        entry("\uD83D\uDC64", "person ब्यक्ति"),
        entry("\uD83D\uDC65", "people group मान्छे"),
        entry("\uD83E\uDDD1", "person adult"),
        entry("\uD83D\uDC76", "baby बच्चा"),
        entry("\uD83D\uDC67", "girl केटी"),
        entry("\uD83D\uDC66", "boy केटा"),
        entry("\uD83D\uDC69", "woman आइमाई"),
        entry("\uD83D\uDC68", "man मान्छे"),
        entry("\uD83D\uDC74", "older woman हजुरआमा"),
        entry("\uD83D\uDC75", "older man हजुरबुबा"),
        entry("\uD83D\uDE4D", "person gesturing no"),
        entry("\uD83D\uDE4E", "person gesturing ok"),
        entry("\uD83D\uDE45", "person facepalm"),
        entry("\uD83D\uDE46", "person shrugging"),
        entry("\uD83D\uDC77", "office worker काम"),
        entry("\uD83D\uDC69\u200D\u2695\uFE0F", "doctor डाक्टर"),
        entry("\uD83D\uDC68\u200D\u2695\uFE0F", "doctor डाक्टर"),
        entry("\uD83D\uDC69\u200D\uD83C\uDFEB", "teacher शिक्षक"),
        entry("\uD83D\uDC68\u200D\uD83C\uDFEB", "teacher शिक्षक"),
        entry("\uD83D\uDC69\u200D\uD83C\uDF93", "student विद्यार्थी"),
        entry("\uD83D\uDC68\u200D\uD83C\uDF93", "student विद्यार्थी"),
        entry("\uD83D\uDC69\u200D\uD83C\uDF73", "cook"),
        entry("\uD83D\uDC68\u200D\uD83C\uDF73", "cook"),
        entry("\uD83D\uDC69\u200D\uD83D\uDCBB", "developer programmer code"),
        entry("\uD83D\uDC68\u200D\uD83D\uDCBB", "developer programmer code"),
        entry("\uD83D\uDD75\uFE0F", "detective police"),
        entry("\uD83D\uDC6E", "police officer प्रहरी"),
        entry("\uD83D\uDC82", "guard सुरक्षा"),
        entry("\uD83D\uDC77\u200D\u2642\uFE0F", "construction worker"),
        entry("\uD83E\uDDD1\u200D\uD83C\uDF3E", "farmer किसान"),
        entry("\uD83D\uDC78", "princess"),
        entry("\uD83E\uDD34", "superhero"),
        entry("\uD83E\uDDD9", "mage wizard"),
        entry("\uD83E\uDDDD", "elf"),
        entry("\uD83D\uDC7B", "ghost"),
        entry("\uD83D\uDC80", "skull death"),
        entry("\uD83E\uDDDB", "zombie"),
        entry("\uD83D\uDC83", "dancer dance नाच"),
        entry("\uD83D\uDD7A", "dancer man"),
        entry("\uD83D\uDC6F", "people with bunny ears"),
        entry("\uD83D\uDC91", "couple love माया"),
        entry("\uD83D\uDC8F", "couple kiss"),
        entry("\uD83D\uDC6A", "family परिवार"),
    )

    val ANIMALS: List<EmojiEntry> = listOf(
        entry("\uD83D\uDC36", "dog कुकुर"),
        entry("\uD83D\uDC31", "cat बिरालो"),
        entry("\uD83D\uDC2D", "mouse मुसा"),
        entry("\uD83D\uDC39", "hamster"),
        entry("\uD83D\uDC30", "rabbit खरायो"),
        entry("\uD83E\uDD8A", "fox"),
        entry("\uD83D\uDC3B", "bear भालु"),
        entry("\uD83D\uDC3C", "panda"),
        entry("\uD83D\uDC28", "koala"),
        entry("\uD83D\uDC2F", "tiger बाघ"),
        entry("\uD83E\uDD81", "lion सिंह"),
        entry("\uD83D\uDC2E", "cow गाई"),
        entry("\uD83D\uDC37", "pig सुँगुर"),
        entry("\uD83D\uDC3E", "boar बँदेल"),
        entry("\uD83D\uDC38", "frog भ्यागुता"),
        entry("\uD83D\uDC35", "monkey बाँदर"),
        entry("\uD83D\uDE48", "monkey see no evil"),
        entry("\uD83D\uDC12", "sheep भेडा"),
        entry("\uD83D\uDC10", "goat बाख्रा"),
        entry("\uD83D\uDC2A", "horse घोडा"),
        entry("\uD83E\uDD84", "unicorn"),
        entry("\uD83D\uDC1D", "bee मौरी"),
        entry("\uD83E\uDD8B", "butterfly पुतली"),
        entry("\uD83D\uDC1B", "bug कीरा"),
        entry("\uD83D\uDC1C", "ant कमिला"),
        entry("\uD83D\uDD77\uFE0F", "spider माकुरा"),
        entry("\uD83D\uDC22", "turtle"),
        entry("\uD83D\uDC0D", "snake सर्प साँप"),
        entry("\uD83E\uDD8E", "lizard"),
        entry("\uD83D\uDC0A", "crocodile गोही"),
        entry("\uD83D\uDC2C", "dolphin"),
        entry("\uD83D\uDC33", "whale"),
        entry("\uD83D\uDC1F", "fish माछा"),
        entry("\uD83D\uDC20", "tropical fish माछा"),
        entry("\uD83D\uDC19", "octopus"),
        entry("\uD83D\uDC1A", "shell"),
        entry("\uD83E\uDD80", "crab"),
        entry("\uD83D\uDC1E", "bee bug"),
        entry("\uD83D\uDC1B", "bug"),
        entry("\uD83D\uDC13", "bird चरा"),
        entry("\uD83D\uDC24", "baby chick"),
        entry("\uD83D\uDC25", "hatching chick"),
        entry("\uD83D\uDC26", "chicken कुखुरा"),
        entry("\uD83D\uDC27", "penguin"),
        entry("\uD83D\uDD4A\uFE0F", "dove शान्ति peace"),
        entry("\uD83E\uDD85", "eagle चिल"),
        entry("\uD83E\uDD86", "duck हाँस"),
        entry("\uD83E\uDD89", "owl उल्लु"),
        entry("\uD83E\uDD9C", "parrot सुँगा"),
        entry("\uD83E\uDD9A", "swan"),
        entry("\uD83D\uDC18", "elephant हात्ती"),
        entry("\uD83E\uDD8F", "rhino गैंडा"),
        entry("\uD83D\uDC2B", "buffalo भैंसी"),
        entry("\uD83D\uDC03", "ox गोरु"),
        entry("\uD83D\uDC0E", "horse race"),
        entry("\uD83E\uDD93", "deer मृग"),
        entry("\uD83D\uDC2F", "tiger"),
        entry("\uD83E\uDD8C", "leopard चितुवा"),
        entry("\uD83D\uDC3A", "wolf ब्वाँसो"),
        entry("\uD83E\uDD8A", "fox फ्याउरो"),
        entry("\uD83D\uDC3F\uFE0F", "raccoon"),
        entry("\uD83E\uDDA5", "otter"),
        entry("\uD83D\uDC3B", "bear"),
        entry("\uD83D\uDC08", "cat face"),
        entry("\uD83D\uDC15", "dog face"),
        entry("\uD83D\uDC29", "tiger face"),
        entry("\uD83E\uDD88", "swan bird"),
    )

    val FOOD: List<EmojiEntry> = listOf(
        entry("\uD83C\uDF4F", "apple स्याउ"),
        entry("\uD83C\uDF4E", "orange सुन्तला"),
        entry("\uD83C\uDF50", "pear"),
        entry("\uD83C\uDF51", "peach"),
        entry("\uD83C\uDF49", "grapes अंगुर"),
        entry("\uD83C\uDF53", "strawberry"),
        entry("\uD83C\uDF48", "melon"),
        entry("\uD83C\uDF4C", "banana केरा"),
        entry("\uD83C\uDF4A", "tangerine सुन्तला"),
        entry("\uD83C\uDF47", "lemon कागती"),
        entry("\uD83C\uDF52", "cherry"),
        entry("\uD83C\uDF51", "peach"),
        entry("\uD83E\uDD65", "mango आँप"),
        entry("\uD83C\uDF4D", "pineapple"),
        entry("\uD83E\uDD51", "avocado"),
        entry("\uD83C\uDF45", "tomato गोलभेँडा"),
        entry("\uD83C\uDF46", "eggplant"),
        entry("\uD83E\uDD55", "potato आलु"),
        entry("\uD83E\uDDC5", "onion प्याज"),
        entry("\uD83E\uDDC4", "cucumber काँक्रा"),
        entry("\uD83E\uDD66", "broccoli रायो"),
        entry("\uD83E\uDD6C", "leafy green साग"),
        entry("\uD83C\uDF3D", "rice भात"),
        entry("\uD83C\uDF5A", "cooked rice भात"),
        entry("\uD83C\uDF5B", "curry तरकारी"),
        entry("\uD83C\uDF5C", "steaming bowl"),
        entry("\uD83C\uDF35", "ramen noodle"),
        entry("\uD83C\uDF5D", "spaghetti नुडल्स"),
        entry("\uD83C\uDF63", "roasted sweet potato"),
        entry("\uD83C\uDF64", "oden momo"),
        entry("\uD83C\uDF7C", "bread रोटी"),
        entry("\uD83E\uDD50", "baguette bread"),
        entry("\uD83E\uDD56", "croissant"),
        entry("\uD83E\uDD68", "flatbread roti रोटी"),
        entry("\uD83E\uDDC0", "cheese चीज"),
        entry("\uD83E\uDD69", "bacon"),
        entry("\uD83C\uDF56", "meat मासु"),
        entry("\uD83C\uDF57", "poultry मासु"),
        entry("\uD83C\uDF5E", "hamburger"),
        entry("\uD83C\uDF5F", "fries"),
        entry("\uD83C\uDF54", "burger"),
        entry("\uD83C\uDF55", "pizza"),
        entry("\uD83C\uDF2D", "hot dog"),
        entry("\uD83E\uDD6A", "sandwich"),
        entry("\uD83E\uDD6B", "taco"),
        entry("\uD83C\uDF2E", "burrito"),
        entry("\uD83C\uDF69", "dumpling मःम"),
        entry("\uD83C\uDF6A", "doughnut"),
        entry("\uD83C\uDF6B", "cookie"),
        entry("\uD83C\uDF70", "cake केक"),
        entry("\uD83E\uDDC1", "cupcake"),
        entry("\uD83C\uDF6D", "candy मिठाई"),
        entry("\uD83C\uDF6C", "ice cream आइसक्रिम"),
        entry("\uD83C\uDF66", "shaved ice"),
        entry("\uD83C\uDF6E", "custard"),
        entry("\uD83C\uDF6F", "honey मह"),
        entry("\u2615", "coffee चिया tea hot"),
        entry("\uD83C\uDF75", "tea चिया"),
        entry("\uD83E\uDDC3", "teapot चियादानी"),
        entry("\uD83E\uDD5B", "milk दूध"),
        entry("\uD83E\uDD5A", "egg अण्डा"),
        entry("\uD83E\uDDC8", "salt नुन"),
        entry("\uD83C\uDF7A", "beer"),
        entry("\uD83E\uDD42", "water पानी"),
        entry("\uD83E\uDD64", "cup straw juice"),
        entry("\uD83E\uDD43", "bubble tea"),
        entry("\uD83E\uDD65", "mango आँप fruit"),
    )

    val TRAVEL: List<EmojiEntry> = listOf(
        entry("\uD83D\uDE97", "car गाडी"),
        entry("\uD83D\uDE95", "taxi ट्याक्सी"),
        entry("\uD83D\uDE99", "bus बस"),
        entry("\uD83D\uDE8C", "bus बस"),
        entry("\uD83D\uDE8E", "minibus बस"),
        entry("\uD83D\uDE93", "ambulance एम्बुलेन्स"),
        entry("\uD83D\uDE92", "fire engine"),
        entry("\uD83D\uDE91", "police car प्रहरी"),
        entry("\uD83D\uDE9A", "truck ट्रक"),
        entry("\uD83D\uDE9B", "truck"),
        entry("\uD83D\uDE9C", "tractor ट्रयाक्टर"),
        entry("\uD83C\uDFCD\uFE0F", "motorcycle मोटरसाइकल"),
        entry("\uD83D\uDEB2", "bicycle साइकल"),
        entry("\uD83D\uDEF4", "scooter"),
        entry("\uD83D\uDEB4", "person walking पैदल"),
        entry("\uD83C\uDFC3", "person running दौड"),
        entry("\uD83D\uDE82", "train रेल"),
        entry("\uD83D\uDE85", "bullet train"),
        entry("\uD83D\uDE87", "metro"),
        entry("\uD83D\uDE89", "station स्टेशन"),
        entry("\uD83D\uDE8B", "tram"),
        entry("\u2708\uFE0F", "airplane हवाईजहाज"),
        entry("\uD83D\uDEE9\uFE0F", "airplane departure"),
        entry("\uD83D\uDE81", "small airplane"),
        entry("\uD83D\uDE80", "rocket"),
        entry("\uD83D\uDEF8", "flying saucer"),
        entry("\uD83D\uDEA2", "ship जहाज"),
        entry("\u26F5", "sailboat"),
        entry("\uD83D\uDEF6", "canoe डुंगा"),
        entry("\uD83D\uDEF5", "canoe"),
        entry("\uD83C\uDFCD", "motorcycle"),
        entry("\uD83D\uDEA1", "helicopter हेलिकप्टर"),
        entry("\uD83D\uDEA0", "cable car"),
        entry("\uD83D\uDE9E", "trolleybus"),
        entry("\u26FD", "fuel pump पेट्रोल"),
        entry("\uD83D\uDEA6", "traffic light बत्ती"),
        entry("\uD83D\uDEA7", "construction निर्माण"),
        entry("\uD83D\uDDFF", "world map"),
        entry("\uD83D\uDDFA\uFE0F", "map नक्सा"),
        entry("\uD83D\uDCCC", "pin location ठाउँ"),
        entry("\uD83C\uDFD4\uFE0F", "snow mountain हिमाल"),
        entry("\u26F0\uFE0F", "mountain हिमाल"),
        entry("\uD83C\uDFD5\uFE0F", "camping"),
        entry("\uD83C\uDFD6\uFE0F", "beach"),
        entry("\uD83C\uDFDD\uFE0F", "desert"),
        entry("\uD83C\uDFDE\uFE0F", "island"),
        entry("\uD83C\uDFD7\uFE0F", "national park"),
        entry("\uD83C\uDFE0", "house घर"),
        entry("\uD83C\uDFE1", "house with garden घर"),
        entry("\uD83C\uDFE2", "office building अफिस"),
        entry("\uD83C\uDFE5", "hospital अस्पताल"),
        entry("\uD83C\uDFEB", "school विद्यालय"),
        entry("\uD83C\uDFE8", "hotel होटल"),
        entry("\uD83C\uDFEF", "castle दरबार"),
        entry("\uD83D\uDC92", "temple मन्दिर"),
        entry("\uD83D\uDD4C", "place of worship"),
        entry("\uD83D\uDDFC", "shrine"),
        entry("\u26E9\uFE0F", "shinto shrine"),
        entry("\uD83C\uDF09", "mount fuji"),
        entry("\uD83D\uDDFD", "tokyo tower"),
        entry("\uD83C\uDF0B", "fountain"),
        entry("\uD83C\uDF0C", "moon"),
        entry("\uD83C\uDF1E", "sun घाम"),
        entry("\u2B50", "star तारा"),
        entry("\uD83C\uDF08", "rainbow इन्द्रेणी"),
        entry("\u2600\uFE0F", "sun घाम"),
        entry("\uD83C\uDF24\uFE0F", "sun clouds घाम"),
        entry("\u26C5", "partly cloudy"),
        entry("\uD83C\uDF25\uFE0F", "cloud sun"),
        entry("\u2601\uFE0F", "cloud बादल"),
        entry("\uD83C\uDF26\uFE0F", "rain clouds वर्षा"),
        entry("\uD83C\uDF27\uFE0F", "rain वर्षा"),
        entry("\u26C8\uFE0F", "thunder चट्याङ"),
        entry("\u2744\uFE0F", "snow हिउँ"),
        entry("\u26A1", "lightning चट्याङ"),
        entry("\uD83C\uDF2A\uFE0F", "tornado"),
        entry("\uD83C\uDF0A", "wave लहर"),
        entry("\uD83C\uDFD4", "mountain"),
    )

    val ACTIVITIES: List<EmojiEntry> = listOf(
        entry("\u26BD", "football फुटबल"),
        entry("\uD83C\uDFC0", "basketball"),
        entry("\uD83C\uDFC8", "volleyball"),
        entry("\u26BE", "baseball"),
        entry("\uD83C\uDFBE", "tennis"),
        entry("\uD83C\uDFD0", "cricket क्रिकेट"),
        entry("\uD83C\uDFD1", "field hockey"),
        entry("\uD83C\uDFD3", "ping pong"),
        entry("\uD83C\uDFF8", "badminton ब्याडमिन्टन"),
        entry("\uD83E\uDD4A", "boxing मुक्का"),
        entry("\uD83E\uDD4B", "martial arts"),
        entry("\u26F3", "golf"),
        entry("\uD83C\uDFF9", "fishing माछा"),
        entry("\uD83C\uDFA3", "fishing pole"),
        entry("\uD83C\uDFBD", "running shirt race"),
        entry("\u26F7\uFE0F", "skier"),
        entry("\uD83C\uDFC2", "snowboarder"),
        entry("\uD83C\uDFCB\uFE0F", "weight lifting"),
        entry("\uD83E\uDD38", "gymnastics"),
        entry("\uD83C\uDFC4", "surfer"),
        entry("\uD83C\uDFCA", "swimmer पौडी"),
        entry("\uD83D\uDEB5", "cyclist साइकल"),
        entry("\uD83C\uDFC7", "horse racing"),
        entry("\uD83E\uDD3C", "wrestling"),
        entry("\uD83E\uDD3D", "water polo"),
        entry("\uD83E\uDD3E", "handball"),
        entry("\uD83C\uDFAF", "direct hit target"),
        entry("\uD83C\uDFB1", "video game खेल"),
        entry("\uD83D\uDD79\uFE0F", "video game"),
        entry("\uD83C\uDFB2", "dice"),
        entry("\uD83E\uDDE9", "puzzle"),
        entry("\u265F\uFE0F", "chess"),
        entry("\uD83C\uDFAD", "theater नाटक"),
        entry("\uD83C\uDFA8", "art"),
        entry("\uD83C\uDFAC", "movie फिल्म"),
        entry("\uD83C\uDFA4", "microphone गीत"),
        entry("\uD83C\uDFA7", "headphones"),
        entry("\uD83C\uDFB5", "music note संगीत गीत"),
        entry("\uD83C\uDFB6", "music notes संगीत"),
        entry("\uD83C\uDFB8", "guitar"),
        entry("\uD83E\uDD41", "drum"),
        entry("\uD83C\uDFB9", "piano"),
        entry("\uD83C\uDFA4", "microphone"),
        entry("\uD83C\uDFC6", "trophy पुरस्कार"),
        entry("\uD83E\uDD47", "gold medal"),
        entry("\uD83E\uDD48", "silver medal"),
        entry("\uD83E\uDD49", "bronze medal"),
        entry("\uD83C\uDFF5", "reminder ribbon"),
        entry("\uD83C\uDF81", "gift उपहार"),
        entry("\uD83C\uDF89", "party popper"),
        entry("\uD83C\uDF8A", "confetti"),
        entry("\uD83C\uDF88", "balloon"),
        entry("\uD83C\uDF86", "fireworks"),
        entry("\u2728", "sparkles चमक"),
        entry("\uD83C\uDF1F", "glowing star"),
        entry("\uD83C\uDF87", "sparkler"),
        entry("\uD83E\uDE84", "mirror ball"),
    )

    val OBJECTS: List<EmojiEntry> = listOf(
        entry("\uD83D\uDCF1", "mobile phone फोन"),
        entry("\uD83D\uDCF2", "phone call"),
        entry("\u260E\uFE0F", "telephone फोन"),
        entry("\uD83D\uDCBB", "laptop कम्प्युटर"),
        entry("\uD83D\uDCBB\uFE0F", "laptop कम्प्युटर"),
        entry("\uD83D\uDDA5\uFE0F", "desktop computer"),
        entry("\uD83D\uDDA8\uFE0F", "printer"),
        entry("\u2328\uFE0F", "keyboard किबोर्ड"),
        entry("\uD83D\uDDB1\uFE0F", "mouse"),
        entry("\uD83D\uDCBD", "computer disk"),
        entry("\uD83D\uDCBE", "floppy disk"),
        entry("\uD83D\uDCBF", "cd"),
        entry("\uD83D\uDCF7", "camera क्यामेरा"),
        entry("\uD83D\uDCF8", "camera flash फोटो"),
        entry("\uD83D\uDCF9", "video camera भिडियो"),
        entry("\uD83C\uDFA5", "movie camera"),
        entry("\uD83D\uDCFA", "television टिभी"),
        entry("\uD83D\uDCFB", "radio रेडियो"),
        entry("\uD83C\uDF99\uFE0F", "studio microphone"),
        entry("\u23F0", "alarm clock घडी"),
        entry("\u231A", "watch घडी"),
        entry("\u23F1\uFE0F", "stopwatch"),
        entry("\u23F2\uFE0F", "timer"),
        entry("\uD83D\uDD70\uFE0F", "mantelpiece clock"),
        entry("\uD83C\uDF17", "hourglass"),
        entry("\uD83D\uDD0B", "battery"),
        entry("\uD83D\uDD0C", "electric plug बिजुली"),
        entry("\uD83D\uDCA1", "light bulb बत्ती idea"),
        entry("\uD83D\uDD26", "flashlight"),
        entry("\uD83D\uDD6F\uFE0F", "candle मैनबत्ती"),
        entry("\uD83D\uDD11", "key चाबी"),
        entry("\uD83D\uDD12", "locked lock ताला"),
        entry("\uD83D\uDD13", "unlocked"),
        entry("\uD83D\uDD28", "hammer हथौडा"),
        entry("\uD83E\uDE93", "axe बन्चरो"),
        entry("\uD83D\uDD27", "wrench"),
        entry("\uD83D\uDD29", "nut and bolt"),
        entry("\u2699\uFE0F", "gear"),
        entry("\u2697\uFE0F", "alembic"),
        entry("\uD83D\uDD2C", "microscope"),
        entry("\uD83D\uDD2D", "telescope"),
        entry("\uD83D\uDCF0", "newspaper समाचार"),
        entry("\uD83D\uDCD6", "book किताब"),
        entry("\uD83D\uDCD5", "open book किताब"),
        entry("\uD83D\uDCD3", "notebook"),
        entry("\uD83D\uDCDD", "memo"),
        entry("\u270F\uFE0F", "pencil"),
        entry("\uD83D\uDD8A\uFE0F", "pen कलम"),
        entry("\uD83D\uDD8B\uFE0F", "paintbrush"),
        entry("\uD83D\uDD8C\uFE0F", "crayon"),
        entry("\uD83D\uDCC4", "page कागज"),
        entry("\uD83D\uDCC1", "folder"),
        entry("\uD83D\uDDC2\uFE0F", "file cabinet"),
        entry("\uD83D\uDCC5", "calendar पात्रो"),
        entry("\uD83D\uDCC6", "tear off calendar"),
        entry("\uD83D\uDCC8", "chart increasing बढ्नु"),
        entry("\uD83D\uDCC9", "chart decreasing"),
        entry("\uD83D\uDCCA", "bar chart"),
        entry("\uD83D\uDCCB", "clipboard"),
        entry("\uD83D\uDCCC", "pushpin"),
        entry("\uD83D\uDCCE", "paperclip"),
        entry("\uD83D\uDDD1\uFE0F", "wastebasket"),
        entry("\uD83D\uDCB0", "money bag पैसा"),
        entry("\uD83D\uDCB5", "dollar पैसा"),
        entry("\uD83D\uDCB8", "credit card"),
        entry("\uD83D\uDCB3", "gem रत्न"),
        entry("\u2696\uFE0F", "balance scale"),
        entry("\uD83D\uDD27", "wrench tool"),
        entry("\uD83E\uDDF1", "basketball hoops"),
        entry("\uD83D\uDED2", "shopping cart किनमेल"),
        entry("\uD83E\uDDFA", "shopping bags"),
        entry("\uD83C\uDF92", "backpack झोला"),
        entry("\uD83E\uDDF3", "toolbox"),
        entry("\uD83E\uDDF4", "magnet"),
        entry("\uD83E\uDDF9", "soap साबुन"),
        entry("\uD83E\uDDF8", "toothbrush"),
        entry("\uD83D\uDEC1", "shower"),
        entry("\uD83D\uDECB\uFE0F", "bed"),
        entry("\uD83D\uDECF\uFE0F", "toilet"),
        entry("\uD83E\uDDF7", "chair"),
        entry("\uD83E\uDDF9", "soap"),
        entry("\uD83D\uDD6E", "bell बेल"),
        entry("\uD83D\uDD14", "bell"),
        entry("\uD83D\uDCE3", "loudspeaker"),
        entry("\uD83D\uDCE2", "loudspeaker announce"),
        entry("\uD83D\uDD50", "speech balloon"),
        entry("\uD83D\uDCAC", "speech कुरा"),
        entry("\uD83D\uDCAD", "thought bubble"),
        entry("\uD83D\uDD0D", "magnifying glass खोज"),
        entry("\uD83D\uDD0E", "magnifying glass right"),
        entry("\uD83D\uDD12", "lock"),
        entry("\u2693", "anchor"),
        entry("\uD83E\uDDED", "ring"),
        entry("\uD83D\uDC8D", "ring love"),
        entry("\uD83C\uDFF7\uFE0F", "label"),
        entry("\uD83D\uDE80", "rocket"),
    )

    val SYMBOLS: List<EmojiEntry> = listOf(
        entry("\u2764\uFE0F", "red heart माया love"),
        entry("\uD83E\uDDE1", "orange heart"),
        entry("\uD83D\uDC9B", "yellow heart"),
        entry("\uD83D\uDC9A", "green heart"),
        entry("\uD83D\uDC99", "blue heart"),
        entry("\uD83D\uDC9C", "purple heart"),
        entry("\uD83D\uDDA4", "black heart"),
        entry("\uD83E\uDD0D", "white heart"),
        entry("\uD83E\uDD0E", "brown heart"),
        entry("\uD83D\uDC94", "broken heart दुख"),
        entry("\u2763\uFE0F", "heart exclamation"),
        entry("\uD83D\uDC95", "two hearts"),
        entry("\uD83D\uDC9E", "revolving hearts"),
        entry("\uD83D\uDC93", "beating heart"),
        entry("\uD83D\uDC97", "heart decoration"),
        entry("\uD83D\uDC96", "sparkling heart"),
        entry("\uD83D\uDC98", "growing heart"),
        entry("\uD83D\uDC9D", "heart with arrow"),
        entry("\uD83D\uDC9F", "heart ribbon"),
        entry("\uD83D\uDC8B", "kiss mark माया"),
        entry("\uD83D\uDCAF", "hundred points"),
        entry("\uD83D\uDCA2", "anger symbol रिस"),
        entry("\uD83D\uDCA5", "collision"),
        entry("\uD83D\uDCA6", "dizzy symbol"),
        entry("\uD83D\uDCA8", "sweat droplets"),
        entry("\uD83D\uDCA9", "pile of poo"),
        entry("\uD83D\uDCAB", "dash symbol"),
        entry("\uD83D\uDD25", "fire आगो hot"),
        entry("\u2B50", "star तारा"),
        entry("\uD83C\uDF1F", "glowing star"),
        entry("\u2728", "sparkles"),
        entry("\u26A1", "high voltage"),
        entry("\uD83D\uDCA4", "zzz sleep"),
        entry("\uD83D\uDCA3", "bomb"),
        entry("\uD83D\uDCAF", "100"),
        entry("\uD83C\uDD97", "free button"),
        entry("\uD83C\uDD92", "new button"),
        entry("\uD83C\uDD95", "top button"),
        entry("\uD83C\uDD99", "up button"),
        entry("\uD83D\uDD1D", "cool button"),
        entry("\u2705", "check mark सही"),
        entry("\u274C", "cross mark गलत"),
        entry("\u274E", "cross mark box"),
        entry("\u2757", "exclamation"),
        entry("\u2753", "question"),
        entry("\u2755", "interrobang"),
        entry("\u26A0\uFE0F", "warning सावधान"),
        entry("\uD83D\uDEAB", "prohibited"),
        entry("\u2696\uFE0F", "scales justice"),
        entry("\u267B\uFE0F", "recycle"),
        entry("\uD83D\uDD31", "peace शान्ति"),
        entry("\u262E\uFE0F", "peace symbol शान्ति"),
        entry("\u271D\uFE0F", "cross"),
        entry("\u262F\uFE0F", "om ॐ धर्म"),
        entry("\u2638\uFE0F", "wheel of dharma धर्म"),
        entry("\uD83D\uDD49\uFE0F", "star and crescent"),
        entry("\u2721\uFE0F", "star of david"),
        entry("\u2600\uFE0F", "sun"),
        entry("\uD83C\uDF19", "crescent moon"),
        entry("\u2B06\uFE0F", "arrow up"),
        entry("\u2B07\uFE0F", "arrow down"),
        entry("\u2B05\uFE0F", "arrow left"),
        entry("\u27A1\uFE0F", "arrow right"),
        entry("\uD83D\uDD01", "repeat"),
        entry("\uD83D\uDD00", "shuffle"),
        entry("\u25B6\uFE0F", "play"),
        entry("\u23F8\uFE0F", "pause"),
        entry("\u23F9\uFE0F", "stop"),
        entry("\uD83D\uDD3A", "speaker sound"),
        entry("\uD83D\uDD07", "volume off"),
        entry("\uD83D\uDD08", "volume low"),
        entry("\uD83D\uDD09", "volume high"),
        entry("\uD83D\uDD0A", "loud sound"),
        entry("\uD83D\uDCF6", "signal bars"),
        entry("\uD83D\uDCF5", "vibration"),
        entry("\uD83D\uDD1E", "no mobile phones"),
        entry("\u267F", "wheelchair"),
        entry("\uD83D\uDEBE", "restroom"),
        entry("\uD83D\uDEBB", "restroom sign"),
        entry("\uD83C\uDFA6", "cinema"),
        entry("#\uFE0F\u20E3", "hash keycap"),
        entry("*\uFE0F\u20E3", "asterisk keycap"),
        entry("0\uFE0F\u20E3", "zero keycap"),
        entry("1\uFE0F\u20E3", "one keycap"),
        entry("2\uFE0F\u20E3", "two keycap"),
        entry("3\uFE0F\u20E3", "three keycap"),
        entry("4\uFE0F\u20E3", "four keycap"),
        entry("5\uFE0F\u20E3", "five keycap"),
        entry("6\uFE0F\u20E3", "six keycap"),
        entry("7\uFE0F\u20E3", "seven keycap"),
        entry("8\uFE0F\u20E3", "eight keycap"),
        entry("9\uFE0F\u20E3", "nine keycap"),
    )

    val FLAGS: List<EmojiEntry> = listOf(
        entry("\uD83C\uDDF3\uD83C\uDDF5", "nepal नेपाल flag"),
        entry("\uD83C\uDDEE\uD83C\uDDF3", "india भारत flag"),
        entry("\uD83C\uDDFA\uD83C\uDDF8", "usa america flag"),
        entry("\uD83C\uDDEC\uD83C\uDDE7", "uk britain flag"),
        entry("\uD83C\uDDE8\uD83C\uDDF3", "china चीन flag"),
        entry("\uD83C\uDDEF\uD83C\uDDF5", "japan flag"),
        entry("\uD83C\uDDF0\uD83C\uDDF7", "korea flag"),
        entry("\uD83C\uDDE6\uD83C\uDDFA", "australia flag"),
        entry("\uD83C\uDDE8\uD83C\uDDE6", "canada flag"),
        entry("\uD83C\uDDE9\uD83C\uDDEA", "germany flag"),
        entry("\uD83C\uDDEB\uD83C\uDDF7", "france flag"),
        entry("\uD83C\uDDF7\uD83C\uDDFA", "russia flag"),
        entry("\uD83C\uDDE7\uD83C\uDDF7", "brazil flag"),
        entry("\uD83C\uDDFF\uD83C\uDDE6", "south africa flag"),
        entry("\uD83C\uDDE6\uD83C\uDDEA", "uae dubai flag"),
        entry("\uD83C\uDDF8\uD83C\uDDE6", "saudi arabia flag"),
        entry("\uD83C\uDDF6\uD83C\uDDE6", "qatar flag"),
        entry("\uD83C\uDDF2\uD83C\uDDFE", "malaysia flag"),
        entry("\uD83C\uDDF8\uD83C\uDDEC", "singapore flag"),
        entry("\uD83C\uDFF3\uFE0F", "white flag"),
        entry("\uD83C\uDFF4", "black flag"),
        entry("\uD83C\uDFF3\uFE0F\u200D\uD83C\uDF08", "rainbow flag"),
        entry("\uD83C\uDFC1", "chequered flag"),
        entry("\uD83D\uDEA9", "triangular flag"),
        entry("\uD83C\uDDF1\uD83C\uDDF0", "sri lanka flag"),
        entry("\uD83C\uDDE7\uD83C\uDDE9", "bangladesh flag"),
        entry("\uD83C\uDDF5\uD83C\uDDF0", "pakistan flag"),
        entry("\uD83C\uDDE7\uD83C\uDDF9", "bhutan flag"),
        entry("\uD83C\uDDF9\uD83C\uDDED", "thailand flag"),
        entry("\uD83C\uDFF4\u200D\u2620\uFE0F", "pirate flag"),
    )

    /** All categories in tab order with their lists. */
    val byCategory: Map<EmojiCategory, List<EmojiEntry>> = mapOf(
        EmojiCategory.SMILEYS to SMILEYS,
        EmojiCategory.PEOPLE to PEOPLE,
        EmojiCategory.ANIMALS to ANIMALS,
        EmojiCategory.FOOD to FOOD,
        EmojiCategory.TRAVEL to TRAVEL,
        EmojiCategory.ACTIVITIES to ACTIVITIES,
        EmojiCategory.OBJECTS to OBJECTS,
        EmojiCategory.SYMBOLS to SYMBOLS,
        EmojiCategory.FLAGS to FLAGS,
    )

    /** Flat catalog used by the search field. Built once, never mutated. */
    val all: List<EmojiEntry> = byCategory.values.flatten()

    /**
     * Keyword search. Case-insensitive substring match over the keyword blob,
     * which contains English and Nepali terms, so "माया", "love" and "heart" all
     * find ❤️. Returns at most [limit] entries.
     */
    fun search(query: String, limit: Int = 60): List<EmojiEntry> {
        val trimmed = query.trim().lowercase()
        if (trimmed.isEmpty()) return emptyList()
        val result = ArrayList<EmojiEntry>(limit)
        for (entry in all) {
            if (entry.keywords.contains(trimmed) || entry.emoji == trimmed) {
                result += entry
                if (result.size >= limit) break
            }
        }
        return result
    }

    fun entriesFor(category: EmojiCategory): List<EmojiEntry> =
        byCategory[category] ?: emptyList()
}
